k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: kind-kind
  currentCluster: kind-kind
  clusters:
    a1c086db8a0e442cab2cc90423908ff2-6a9ef04c99a6b72f-elb-us-east-1-amazonaws-com:6443:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - openshift-monitoring
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    a4a5f18084e5948b99be4b912dd1eb20-623e7febe5fde90f-elb-us-east-1-amazonaws-com:6443:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - openshift-monitoring
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-ci-ln-2mw7m7t-76ef8-origin-ci-int-aws-dev-rhcloud-com:6443:
      namespace:
        active: openshift-monitoring
        lockFavorites: false
        favorites:
        - openshift-monitoring
        - all
        - default
      view:
        active: service
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-ci-ln-k4129l2-76ef8-origin-ci-int-aws-dev-rhcloud-com:6443:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: servicemonitor
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-ci-ln-kgxipbb-76ef8-aws-2-ci-openshift-org:6443:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-ci-ln-y6kfc2b-76ef8-origin-ci-int-aws-dev-rhcloud-com:6443:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: prometheus
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    api-rhamilto-devcluster-openshift-com:6443:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - openshift-monitoring
        - all
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    kind-kind:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - default
      view:
        active: statefulset
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-rexagod
